// ==============================
// ATLAS DIGITAL - CADASTRO
// ==============================

// Formulário
const formCadastro = document.getElementById("formCadastro");

// Campos
const email = document.getElementById("email");
const senha = document.getElementById("senha");
const confirmarSenha = document.getElementById("confirmar-senha");

// Mensagens de erro 
const erroEmail = document.getElementById("erroEmail");
const erroSenha = document.getElementById("erroSenha");
const erroConfirmarSenha = document.getElementById("erroConfirmarSenha");
